#Arreglos y Clases

##Matrices
Una matriz es un arreglo de tamaño m por n.


\begin{bmatrix}
a_{11} & a_{12} & \dots  & a_{1n} \\
a_{21} & a_{22} & \dots  & a_{2n} \\
\vdots & \vdots & \ddots & \vdots \\
a_{m1} & a_{m2} & \dots  & a_{mn}
\end{bmatrix}



In [ ]:
A = [[1,2,3],[4,5,6],[7,8,9]]
print(A)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [ ]:
#Otra Matriz
B =[[21,34,40],[71,17,77],[73,81,28]]
print(A+B)

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [21, 34, 40], [71, 17, 77], [73, 81, 28]]


In [ ]:
2*A

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
A[0][0]

1

##Vectores y listas

In [ ]:
L=A[0]

In [ ]:
M=B[0]

In [ ]:
print(M)

[21, 34, 40]


In [ ]:
a=L[0]
b=M[0]
a+b

22

In [ ]:
a==1

True

In [ ]:
len(L)==len(M)

True

In [ ]:
[L[0]+M[0],L[1]+M[1],L[2]+M[2]]

[22, 36, 43]

####Creación de funciones globales
La función para crear funciones es `def` que se cierra con un debuyg ( `print` o `return`)

In [ ]:
def Hola():
  print ("Hola, me llamo Marifer")

In [ ]:
Hola()

Hola, me llamo Marifer


In [ ]:
def Saludar(s,n):
  print(f"Hola, me llamo {s} y tengo {n} años")

In [ ]:
Saludar("Marifer", 19)

Hola, me llamo Marifer y tengo 19 años


In [ ]:
def par(i):
  for i in range(i):
    if i%2 ==0 :
      print(f"{i} es par")
    else:
      print(f"{i} es impar")


In [ ]:
par(20)

0 es par
1 es impar
2 es par
3 es impar
4 es par
5 es impar
6 es par
7 es impar
8 es par
9 es impar
10 es par
11 es impar
12 es par
13 es impar
14 es par
15 es impar
16 es par
17 es impar
18 es par
19 es impar


In [ ]:
def suma_vectorial(L, M):
  x = [L[i]+M[i] for i in range(len(L))]
  return x

In [ ]:
L = [1,2,3]
M = [21,34,40]
suma_vectorial(L,M)

[22, 36, 43]

##Módulos o librerías
Conjunto de módulos que contienen código reutilizable para realizar tareas específicas sin necesidad de programarlas desde cero. Estas librerías pueden incluir funciones, clases y métodos que facilitan la programación en distintos ámbitos como matemáticas, análisis de datos, inteligencia artificial, desarrollo web, etc.



In [ ]:
import math
from math import sqrt, pi

In [ ]:
sqrt(68)

8.246211251235321

In [ ]:
pi

3.141592653589793

#El módulo NumPy

La función `array`

In [ ]:
import numpy as np

L_vector = np.array(L)
M_vector = np.array(M)

L_vector + M_vector

array([22, 36, 43])

In [ ]:
C=[9,2,2,2,3,3,2,17,2]
A = [8,1,1,1,2,2,1,16,1]

C_matriz = np.array(C).reshape(3,3)
A_matriz = np.array(A).reshape(3,3)

print(C_matriz)
print(A_matriz)

[[ 9  2  2]
 [ 2  3  3]
 [ 2 17  2]]
[[ 8  1  1]
 [ 1  2  2]
 [ 1 16  1]]


In [ ]:
C_matriz @ A_matriz

array([[76, 45, 15],
       [22, 56, 11],
       [35, 68, 38]])

In [ ]:
A_matriz @ C_matriz

array([[76, 36, 21],
       [17, 42, 12],
       [43, 67, 52]])